{
 "title": "WorkerPool Dashboard",
 "description": "Monitoring of the application server based on WorkerPool\n\nhttps://github.com/EdmondDantes/amphp-pool",
 "tags": [
  "asynchronous",
  "AMPHP",
  "PHP"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Connections RPM",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(worker_connections_accepted[1m]))",
     "legendFormat": "Accepted"
    },
    {
     "expr": "sum by(instance) (rate(worker_connections_processing[1m]))",
     "legendFormat": "Processing"
    },
    {
     "expr": "sum by(instance) (rate(worker_connections_processed[1m]))",
     "legendFormat": "Processed"
    },
    {
     "expr": "sum by(instance) (rate(worker_connections_errors[1m]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Reactors",
   "type": "gauge",
   "description": "The list of worker groups",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(group_name) (worker_group{group_type=\"reactor\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "gauge",
   "description": "The list of worker groups",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(group_name) (worker_group{group_type=\"job\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Services",
   "type": "gauge",
   "description": "The list of worker groups",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(group_name) (worker_group{group_type=\"service\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "application_uptime", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Reloads",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 19, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "application_restarts_count", "legendFormat": "__auto" }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Total memory",
   "type": "timeseries",
   "description": "How to workers used memory PHP",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (worker_php_memory_usage)",
     "legendFormat": "php memory"
    },
    {
     "expr": "sum by(instance) (worker_memory_usage_system)",
     "legendFormat": "system"
    }
   ]
  },
  {
   "title": "Job processing",
   "type": "timeseries",
   "description": "How many jobs is processing",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(worker_job_processed[1m]))",
     "legendFormat": "processed"
    },
    {
     "expr": "sum by(instance) (rate(worker_job_errors[1m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Memory per worker",
   "type": "timeseries",
   "description": "How to workers used memory PHP",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(instance) (worker_php_memory_usage)",
     "legendFormat": "php memory"
    },
    {
     "expr": "max by(instance) (worker_memory_usage_system)",
     "legendFormat": "system"
    }
   ]
  },
  {
   "title": "Jobs memory",
   "type": "timeseries",
   "description": "How to workers used memory PHP",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(instance) (worker_php_memory_usage{group=\"job\"})",
     "legendFormat": "php memory"
    },
    {
     "expr": "max by(instance) (worker_memory_usage_system{group=\"job\"})",
     "legendFormat": "system"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } }
 ]
}